Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "10.0.2.2"
  config.vm.synced_folder "./../data", "/mnt/vagrant", type: "nfs" # This is the line that was added    
  config.vm.provision "shell", path: "provision.sh"
  config.vm.box_download_insecure = true
     config.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
      end
end    