apiVersion: v1
kind: Service
metadata:
  name: php
spec: 
  selector:
    app: php
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec: 
  ports: 
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
  clusterIP: None  
