pipeline {
    agent any
    stages {
        stage('Build') {
            template {
                name 'build'
                parameters {
                    stringParam('GIT_URL', 'ffff')
                }   
                
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}