Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "10.0.2.5"
  config.vm.network "forwarded_port", guest: 8080, host: 8082
  config.vm.box_download_insecure = true
end    