Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "db01"
  config.vm.network "private_network", ip: "10.0.2.6"
  config.vm.network "forwarded_port", guest: 3306, host: 4306
  config.vm.provision "shell", path: "provision.sh"
  config.vm.box_download_insecure = true
end    